# Dachung crack/damage segmentation inference config
classes: ["BG", "CRC", "DLM", "SPL"]
num_classes: 4

model: "deeplabv3plus"
encoder_name: "resnet101"
img_size: 768
stride: 384

palette:
  0: [0, 0, 0]
  1: [255, 0, 0]
  2: [0, 200, 0]
  3: [255, 165, 0]

